URLs:
  githubRawRootURL: https://raw.githubusercontent.com
  githubCovid19RepoURL: https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports
directories:
  covid19Directory: /home/ernie/PycharmProjects/covid-19/webapp/COVID-19-data
  plotImgDirectory: /home/ernie/PycharmProjects/covid-19/webapp/static/images